service: cru-udp-pipeline

provider:
  name: google
  runtime: nodejs10
  project: cru-snowplow-prod-1
  region: us-east4
  credentials: ./keyfile.json
  environment: ${file(serverless/environment.js)}

plugins:
  - serverless-webpack
  - serverless-google-cloudfunctions

functions:
  tealium:
    handler: tealium
#    events:
#      - event:
#          eventType: providers/cloud.pubsub/eventTypes/topic.publish
#          resource: projects/cru-snowplow-prod-1/topics/sp-rt-pipeline-good-prod1

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: yarn
    excludeFiles: '**/*.test.js'
