service: cru-udp-pipeline

provider:
  name: google
  runtime: nodejs10
  project: cru-snowplow-prod-1
  region: us-east4
  credentials: ./keyfile.json
  environment: ${file(serverless/environment.js)}

plugins:
  - serverless-webpack
  - serverless-google-cloudfunctions-amazing

functions:
  tealium:
    handler: tealium
    serviceAccount: ${env:FUNCTION_SERVICE_ACCOUNT}
    events:
      - event:
          eventType: providers/cloud.pubsub/eventTypes/topic.publish
          resource: ${env:SNOWPLOW_PIPELINE_TOPIC}

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: yarn
    excludeFiles: '**/*.test.js'
