service: cru-udp-pipeline
frameworkVersion: '3'
configValidationMode: warn
plugins:
  - serverless-webpack
  - serverless-google-cloudfunctions-amazing

provider:
  name: google
  runtime: nodejs16
  project: cru-snowplow-prod-1
  region: us-east4
  credentials: ./keyfile.json
  environment: ${file(env.js)}

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: yarn
    excludeFiles: '**/*.test.js'
    excludeRegex: \.ts|test|\.map

functions:
  tealium:
    handler: tealium
    serviceAccount: ${env:FUNCTION_SERVICE_ACCOUNT}
    events:
      - event:
          eventType: providers/cloud.pubsub/eventTypes/topic.publish
          resource: ${env:SNOWPLOW_PIPELINE_TOPIC}

  audience:
    handler: audience
    serviceAccount: ${env:FUNCTION_SERVICE_ACCOUNT}
    events:
      - event:
          eventType: providers/cloud.pubsub/eventTypes/topic.publish
          resource: ${env:TEALIUM_AUDIENCE_TOPIC}
  
  acs:
    handler: acs
    serviceAccount: ${env:FUNCTION_SERVICE_ACCOUNT}
    events:
      - event:
          eventType: providers/cloud.pubsub/eventTypes/topic.publish
          resource: ${env:TEALIUM_ACS_TOPIC}

  placement:
    handler: placement
    serviceAccount: ${env:FUNCTION_SERVICE_ACCOUNT}
    events:
      - http: foo
