service: cru-udp-pipeline

provider:
  name: aws
  runtime: nodejs10.x
  stage: production
  region: us-east-1
  environment: ${file(serverless/environment.js)}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - SQS:SendMessage
        - SQS:SendMessageBatch
      Resource:
        - ${env:UDP_EVENTS_SQS_QUEUE_ARN}
  $<<: ${file(serverless/provider.js)}

functions:
  udp-events:
    handler: handlers/events.handler
    timeout: 30
    events:
      - stream:
          arn: ${env:SNOWPLOW_KINESIS_ENRICH_ARN}
          batchSize: 10 # batchSize must be 10 as it's the max for SQS:SendMessageBatch
          startingPosition: LATEST
          enabled: false

package:
  exclude:
    - .git/**
    - test/**
    - '**/*.test.js'
    - '**/*.sql'
    - .deployment/**

plugins:
  - '@cruglobal/serverless-merge-config'
